# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7954c9069f404b6d2ef5b3e26c8e67153b32725ab5b23d7d293aed54255817b68450690895ac71fccd2b260c8e045755094a48a45324068fafccb28acedcbc78

test:
  secret_key_base: a3f0b50183022a1ede58a5053cf3943a4b566ab94970a3c771fa1b3c3967fa554b24fd2d13f8896385adbf12a7d37a5487232e4f5a4a95d232ab11aa41e1a972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
